class CreateCargos < ActiveRecord::Migration[7.1]
  def change
    create_table :cargos,:force => true do |t|
      t.integer :cargo_request_id, :null =>false ,:comment => "本船作業依頼ID"
      t.date :work_date, :null =>false ,:comment => "作業日"
      t.integer :work_class, :limit =>1 ,:comment => "作業区分"
      t.string :move_no, :limit =>16 ,:comment => "動静番号"
      t.integer :serial_no, :limit =>1 ,:comment => "連番"
      t.integer :work_no, :limit =>2 ,:comment => "作業番号"
      t.integer :desp_index ,:comment => "表示順"
      t.string :work_name, :limit =>32 ,:comment => "作業名"
      t.string :work_cd, :limit =>4 ,:comment => "貨物コード"
      t.string :cargo_name, :limit =>32 ,:comment => "貨物名"
      t.integer :io_flg, :limit =>1 ,:comment => "揚積"
      t.string :quantity, :limit =>16 ,:comment => "数量"
      t.string :work_place, :limit =>16 ,:comment => "場所"
      t.time :i_time ,:comment => "出勤時刻"
      t.time :s_time ,:comment => "開始時刻"
      t.time :e_time ,:comment => "終了予定時刻"
      t.integer :dirt_flg, :limit =>1 ,:comment => "汚れ作業"
      t.string :machine_nm, :limit =>32 ,:comment => "荷役機械"
      t.integer :fm_m, :limit =>2 ,:comment => "FM必要人数"
      t.integer :dm_m, :limit =>2 ,:comment => "DM必要人数"
      t.integer :wm_m, :limit =>2 ,:comment => "WM必要人数"
      t.integer :cr_m, :limit =>2 ,:comment => "クレーン必要人数"
      t.integer :ld_m, :limit =>2 ,:comment => "ローダ(主)必要人数"
      t.integer :ld_s, :limit =>2 ,:comment => "ローダ(副)必要人数"
      t.integer :bh_m, :limit =>2 ,:comment => "バックホー(主)必要人数"
      t.integer :bh_s, :limit =>2 ,:comment => "バックホー(副)必要人数"
      t.integer :sl_m, :limit =>2 ,:comment => "船内ローダ(主)必要人数"
      t.integer :sl_s, :limit =>2 ,:comment => "船内ローダ(副)必要人数"
      t.integer :bl_m, :limit =>2 ,:comment => "ブル(主)必要人数"
      t.integer :bl_s, :limit =>2 ,:comment => "ブル(副)必要人数"
      t.integer :lf_m, :limit =>2 ,:comment => "リフト(主)必要人数"
      t.integer :lf_s, :limit =>2 ,:comment => "リフト(副)必要人数"
      t.integer :sc_m, :limit =>2 ,:comment => "SC(主)必要人数"
      t.integer :sc_s, :limit =>2 ,:comment => "SC(副)必要人数"
      t.integer :tl_m, :limit =>2 ,:comment => "TL(主)必要人数"
      t.integer :tl_s, :limit =>2 ,:comment => "TL(副)必要人数"
      t.integer :ot_m, :limit =>2 ,:comment => "その他取扱者人数"
      t.integer :wk_w, :limit =>2 ,:comment => "作業必要人数"
      t.string :note, :limit =>128 ,:comment => "備考"
      t.string :matter1 ,:comment => "申送り事項1"
      t.string :matter2 ,:comment => "申送り事項2"
      t.string :momo_fm ,:comment => "配番メモ（FM"
      t.string :momo_dm ,:comment => "配番メモ（DM"
      t.string :momo_mc ,:comment => "配番メモ（機械"
      t.string :momo_wi ,:comment => "配番メモ（ｳｨﾝﾁ取扱者"
      t.string :momo_dr ,:comment => "配番メモ（取扱者"
      t.string :momo_wk ,:comment => "配番メモ（船内／沿岸"
      t.integer :ob_np, :limit =>1 ,:comment => "OB人数"
      t.integer :hh_np, :limit =>1 ,:comment => "日立埠頭人数"
      t.integer :rk_np, :limit =>1 ,:comment => "労協人数"
      t.integer :wk_np, :limit =>1 ,:comment => "従事者人数"
      t.integer :work_time ,:comment => "作業時間"
      t.integer :orver_time ,:comment => "残業時間"
      t.integer :esta_flg, :limit =>1 ,:comment => "荷役成立"
      t.integer :conf_flg, :limit =>1 ,:comment => "配番完了フラグ"

      t.integer :lock_version, :default=>1 ,:comment => "ロックバージョン"
      t.datetime :created_at, :null =>false ,:comment => "作成日時"
      t.string :created_uid, :limit =>16, :null =>false ,:comment => "新規登録者ID"
      t.datetime :updated_at, :null =>false ,:comment => "最終更新日時"
      t.string :updated_uid, :limit =>16, :null =>false ,:comment => "更新者ID"
      t.datetime :deleted_at ,:comment => "削除日時"
      t.string :deleted_uid, :limit =>16 ,:comment => "削除者ID"
    end
    add_index :cargos, [:work_date], :name =>:cargos_1
  end
end
