class CreateCargoRequests < ActiveRecord::Migration[7.1]
  def change
    create_table :cargo_requests,:force => true do |t|
      t.date :work_date, :null =>false ,:comment => "作業日"
      t.string :department_cd, :limit =>2 ,:comment => "部署コード"
      t.string :department_nm, :limit =>4 ,:comment => "部署名"
      t.integer :work_class, :limit =>1 ,:comment => "作業区分"
      t.string :move_no, :limit =>16 ,:comment => "動静番号"
      t.string :move_no2, :limit =>16 ,:comment => "沿岸作業コード"
      t.integer :serial_no, :limit =>1 ,:comment => "連番"
      t.integer :work_no, :limit =>2 ,:comment => "作業NO"
      t.string :work_name, :limit =>32 ,:comment => "本船名・作業名"
      t.string :work_cd, :limit =>4 ,:comment => "貨物コード"
      t.string :cargo_name, :limit =>32 ,:comment => "貨物名"
      t.integer :io_flg, :limit =>1 ,:comment => "揚積"
      t.string :quantity, :limit =>16 ,:comment => "数量"
      t.string :work_place, :limit =>16 ,:comment => "場所"
      t.time :i_time ,:comment => "出勤時刻"
      t.time :s_time ,:comment => "開始時刻"
      t.time :e_time ,:comment => "終了予定時刻"
      t.integer :dirt_flg, :limit =>1 ,:comment => "汚れ作業"
      t.string :machine_nm, :limit =>32 ,:comment => "荷役機械"
      t.integer :fm_m, :limit =>2 ,:comment => "FM人数"
      t.integer :dm_m, :limit =>2 ,:comment => "DM人数"
      t.integer :wm_m, :limit =>2 ,:comment => "WM人数"
      t.integer :cr_m, :limit =>2 ,:comment => "クレーン人数"
      t.integer :ld_m, :limit =>2 ,:comment => "ローダ(主)人数"
      t.integer :ld_s, :limit =>2 ,:comment => "ローダ(副)人数"
      t.integer :bh_m, :limit =>2 ,:comment => "バックホー(主)人数"
      t.integer :bh_s, :limit =>2 ,:comment => "バックホー(副)人数"
      t.integer :sl_m, :limit =>2 ,:comment => "船内ローダ(主)人数"
      t.integer :sl_s, :limit =>2 ,:comment => "船内ローダ(副)人数"
      t.integer :bl_m, :limit =>2 ,:comment => "ブル(主)人数"
      t.integer :bl_s, :limit =>2 ,:comment => "ブル(副)人数"
      t.integer :lf_m, :limit =>2 ,:comment => "リフト(主)人数"
      t.integer :lf_s, :limit =>2 ,:comment => "リフト(副)人数"
      t.integer :sc_m, :limit =>2 ,:comment => "SC(主)人数"
      t.integer :sc_s, :limit =>2 ,:comment => "SC(副)人数"
      t.integer :tl_m, :limit =>2 ,:comment => "TL(主)人数"
      t.integer :tl_s, :limit =>2 ,:comment => "TL(副)人数"
      t.integer :ot_m, :limit =>2 ,:comment => "その他取扱者人数"
      t.integer :hd_w, :limit =>2 ,:comment => "ハンドル作業人数"
      t.integer :db_w, :limit =>2 ,:comment => "土場清掃作業人数"
      t.integer :hs_w, :limit =>2 ,:comment => "配車山均作業人数"
      t.integer :sn_w, :limit =>2 ,:comment => "船内作業員作業人数"
      t.integer :eg_w, :limit =>2 ,:comment => "沿岸作業員作業人数"
      t.integer :ot_w, :limit =>2 ,:comment => "他作業人数"
      t.integer :wk_w, :limit =>2 ,:comment => "作業員数計"
      t.string :note, :limit =>128 ,:comment => "備考"
      t.string :matter1 ,:comment => "申送り事項1"
      t.string :matter2 ,:comment => "申送り事項2"
      t.integer :esta_flg, :limit =>1 ,:comment => "荷役成立"

      t.integer :lock_version, :default=>1 ,:comment => "ロックバージョン"
      t.datetime :created_at, :null =>false ,:comment => "作成日時"
      t.string :created_uid, :limit =>16, :null =>false ,:comment => "新規登録者ID"
      t.datetime :updated_at, :null =>false ,:comment => "最終更新日時"
      t.string :updated_uid, :limit =>16, :null =>false ,:comment => "更新者ID"
      t.datetime :deleted_at ,:comment => "削除日時"
      t.string :deleted_uid, :limit =>16 ,:comment => "削除者ID"
    end
    add_index :cargo_requests, [:work_date], :name =>:cargo_requests_1
    add_index :cargo_requests, [:work_date,:work_class,:move_no,:move_no2,:serial_no], :name =>:cargo_requests_2 ,:unique => true
  end
end
